### PR TITLE
Fixes for Julia v0.7

### PR DESCRIPTION
**Pull request by VPetukhov**
Hi!

Here I fixed issues with `Nullable`, `readstring`, `AbstractDictionary`, `Markdown` and `reexport`.
This version still doesn't work on Julia 0.7 because of problems in [Blink.jl](https://github.com/JunoLab/Blink.jl/pull/133), which, if I understood correctly, goes further to [WebIO](https://github.com/JuliaGizmos/WebIO.jl/pull/157). Though now it at least can be built.

### CODE REVIEW

**Comment by VPetukhov** [comment]
Sorry, didn't test in on julia 0.6. Are you going to support this version? Should I change my code on Nullables.jl, or can I just change required version of julia?

**Comment by sglyon** [comment]
Thanks for workign on this. 

At this point I am ready to move to support only Julia 0.7/1.0.

Let's change the version number to 0.7.

Once WebIO + friends are ready to go I will make an effort to replace the display mechanisms here with WebIO based codes.

Thanks!

**Comment by sglyon** [comment]
Thank you! I am updating the package for 0.7/1.0 now and will use this as a starting point.

Very helpful ❤️

**Comment by VPetukhov** [comment]
Thank you very much, @sglyon ! You made an awesome package :)

**Pull request merged**
