### PR TITLE
Update to latest WebIO.

### LINKED ISSUE #278: Plots don't display in Jupyter with WebIO v0.8.1
Upon updating WebIO to v0.8.1 from v0.7.0, plots no longer display/mount in Jupyter. This is reproducible (for me) in a clean environment with only IJulia and PlotlyJS added.

With `] st` of
```
(v1.1) pkg> st
    Status `~/.julia/environments/v1.1/Project.toml`
  [7073ff75] IJulia v1.18.1
  [f0f68f2c] PlotlyJS v0.12.3
  [0f1e0344] WebIO v0.8.1
```

running `using IJulia` and `plot(scatter(;y=rand(50)))` doesn't show any plot. (In the Firefox developer console, running the plot cell produces a "Jupyter WebIO extension detected, not mounting.")

After pinning Webio to v0.7.0, running those same commands in jupyter does produce a plot. (And I can see several XHR requests for JS files being made which don't happen with WebIO at v0.8.1.)

I also tried this with on PlotlyJS master with WebIO v0.8.1 which didn't work (no plot).

```
julia> versioninfo()
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

### PR DESCRIPTION
**Pull request by travigd**
This will not pass on CI until https://github.com/JuliaRegistries/General/pull/1473 is merged.

This fixes #278.

### CODE REVIEW

**Comment by travigd** [comment]
Oh, @sglyon you also include a `Manifest.toml` file. Can we get rid of that? I don't think it's common to include that with packages (it's also causing CI to fail because I didn't update it).

**Comment by sglyon** [comment]
Thanks @travigd 

I tested this out and I do get plots in the jupyter notebook, but I couldn't replicate the issues from #278 

Can anyone verify that this does indeed fix #278? cc @halleysfifthinc @jobjob @DhruvaSambrani @jingpengw @ghuba

**Comment by sglyon** [comment]
@travigd I removed the Manifest.toml file from the master branch. Would you be willing to rebase this PR on master so we can check CI?

**Comment by DhruvaSambrani** [comment]
I did 
```
]up
add https://github.com/travigd/PlotlyJS.jl#upgrade-webio-0.8.6
build
precompile
```

Started Jupyter notebook and ran
```
using PlotlyJS
plot([1,2,3,4,5])
```

This gave the following output 
```
┌ Warning: Please upgrade Blink for a smoother integration with WebIO.
│   caller = ip:0x0
└ @ Core :-1
┌ Warning: Accessing `scope.id` is deprecated, use `scopeid(scope)` instead.
│   caller = ip:0x0
└ @ Core :-1
[The Graph rendered correctly]
```
The Blink warning should go once you merge I suppose.
The scope.id warning could be resolved by doing a FindReplace of all scope.id to scopeid(scope).

But
```
using Plots
plotlyjs()
plot([1,2,3,4,5])
```
Gave the old "WebIO not found" error. But I suppose once the new version is released, this issue should go.

**Comment by travigd** [comment]
The scopeid issue is originating form JSExpr I think. We need to release a new version of that.

**Comment by DhruvaSambrani** [comment]
> The scopeid issue is originating form JSExpr I think. We need to release a new version of that.
Shall I make an issue there if you're sure?

**Comment by sglyon** [comment]
I did check PlotlyJS.jl and the scopeid issue is not in this repo. Not sure where it is, but it isn't here 😆

**Comment by DhruvaSambrani** [comment]
So is this ready to be published?

**Comment by travigd** [comment]
I'm not entirely sure it's in JSExpr but that's a strong hunch. I will rebase this later and this it will be ready.

**Pull request merged**
