### PR TITLE
Check for data files before downloading them during build. 

### PR DESCRIPTION
**Pull request by jjstickel**
Occasionally users cannot use curl for downloading (e.g., firewall), and the workaround is to
download the files via web browser and place them in the proper location.

### CODE REVIEW

**Comment by sglyon** [comment]
Thanks @jjstickel . 

I think this is a step in the right direction. One thing I would like to preserve if possible is the behavior that whenever the package is built, the latest version of plotly.js is downloaded. Thus, whenever a user updates PlotlyJS.jl, the bundled javascript is also kept up to date. 

Perhaps a solution that looks like the following could work:

- Checks for file
- Tries to re-download
    - If fails and file already exists, prints a message that says "failed to update FILENAME, but you already have one. Things might continue to work, but if you would like to make sure you have the latest version of FILENAME please use your web-browser to download it from URL and place it in FOLDER"
    - If fails and file doesn't exist print a similar message but change wording to make it clear that the user MUST download the files "by hand" and put them the correct directory
    - if success, don't to anything

What are your thoughts?

**Comment by jjstickel** [comment]
Sure, I follow. However, after I got PlotlyJS installed, it's not exactly what I am looking for (it is also not working with Plots and Julia 0.7 at the moment). So I'm not motivated to do more on this right now. Do you want me to close the PR or leave it for future reference?

**Comment by jjstickel** [comment]
After some more testing, specifically in Jupyter Notebooks, I changed my mind about PotlyJS. I'll get to making the changes you suggest, but it might be a little while.

**Comment by jjstickel** [comment]
Here is my question on discourse:  https://discourse.julialang.org/t/provide-output-message-during-build-0-7-1-x/16497. Nothing real helpful yet.

**Comment by jjstickel** [comment]
I've added a mechanism during __init__() to alert users to warnings in the build log. Let me know if you think this is satisfactory.

**Comment by jjstickel** [comment]
@sglyon, let me know your thoughts when you've had a chance to look at this. Maybe not high priority, but I'll be happy to have it off my virtual desk.

**Comment by sglyon** [comment]
Hi Sorry @jjstickel lost this in my inbox.

Looks good to me. will merge. 

Thank you for contributing!

**Pull request merged**
