### PR TITLE
Added Pages and PlotlyJS.save

### PR DESCRIPTION
**Pull request by EricForgy**
Still needs a lot of cleanup, but it works for SVG and the path to other formats should be clear I think :)

### CODE REVIEW

**Comment by spencerlyon2** [comment]
Hey @EricForgy thanks for working on this!

It is a great start, but I'd like to do a bit of cleanup before I merge. I'll pick up from this commit and integrate these changes into PlotlyJS and open a new PR for you to check out before I merge.

I'll leave this open until we merge it through the forthcoming PR.

**Comment by EricForgy** [comment]
Hi Spencer. Sounds good. That was my intention :) For example, if you do use Pages, then some of your earlier code is probably redundant, e.g. you can use Pages for comm instead of writing your own ZMQ stuff.

**Comment by spencerlyon2** [comment]
Hey @EricForgy sorry it has taken me a bit to get back to this. However, I think I have found some time today and/or tomorrow to work through this.

I want to add Pages as a proper frontend similar to Electron and IJulia. Here's a sketch of what needs to happen for that (this would happen in `src/displays/pages.jl`):

- [ ] Create a `type PagesDisplay <: AbstractPlotlyDisplay`, where the fields contain all the necessary info to display one plot via Pages.jl. The fields might also include a `Condition` to wait on for getting results back from js.
-  [ ] Do anything we need to get pages started up: e.g. `Pages.start()`, `Pages.Callback`, ...
- [ ] Implement the the API methods (for these we can probably just implement `_call_plotlyjs` on the display and share implementation with the `JupterDisplay` version):
    - [ ] `restyle!(p::SyncPlot{PagesDisplay}, ...)`
    - [ ] `relayout!(p::SyncPlot{PagesDisplay}, ...)`
    - [ ] `addtraces!(p::SyncPlot{PagesDisplay}, ...)`
    - [ ] `deletetraces!(p::SyncPlot{PagesDisplay}, ...)`
    - [ ] `movetraces!(p::SyncPlot{PagesDisplay}, ...)`
    - [ ] `redraw!(p::SyncPlot{PagesDisplay}, ...)`
    - [ ] `extendtraces!(p::SyncPlot{PagesDisplay}, ...)`
    - [ ] `prependtraces!(p::SyncPlot{PagesDisplay}, ...)`'
- [ ] Implement `_img_data(p::SyncPlot{PagesDisplay}, format::String)` and `svg_data(p::SyncPlot{PagesDisplay})`

I've probably forgotten something, but that should give us a very good start. 

If you are willing to help with the first 2 points, I think I should be able to handle all the others. I'd like input on the fields of the type to see what you think we need. I will also want help to make sure I get Pages set up in the right way so we can have seamless js <--> jl  communication going forward

**Comment by EricForgy** [comment]
Sounds like a good plan to me. I'm happy to work on this, but we're in crunch mode at the moment at work. I can have a look some time next week :+1:

**Comment by spencerlyon2** [comment]
Not a problem, happy that you'll have some time to work on this.

My nu-fleshed-out idea was that we could implemented `src/display/pages.jl` to be another fully supported frontend that uses the user's browser. We could then forward the jl -> js -> jl communicated needed in the notebook to the pages display machinery. If at a future date we figure out how to get the communication to work properly within IJulia then we can break that link.

What do you think?

**Comment by EricForgy** [comment]
Sounds good to me. Would that also open the door to having a user's browser be used with Plots (which would be super cool)? @tbreloff

**Comment by spencerlyon2** [comment]
It would certainly allow pages to be used from with three plotljs backend. @tbreloff would have to comment on using it for other backends

**Comment by EricForgy** [comment]
It's been so long since I looked at PlotlyJS, I forgot about this PR 😊 

It looks like a lot of improvements have happened and its cool PlotlyBase has been separated 👍 

If you are open to my idea here https://github.com/sglyon/PlotlyJS.jl/issues/184, then maybe we can do something similar for other packages of interest to PlotlyJS. Rather than force other packages to add PlotlyJS, we can just have some optional methods in PlotlyJS that only get loaded if those packages are in scope.

For example, we can have a PlotlyJS.Pages that only gets loaded if someone is already using Pages, e.g.

```julia
> using Pages
> using PlotlyJS
INFO: Loading Pages methods.
```

or

```julia
> using Blink
> using PlotlyJS
INFO: Loading Blink methods.
```

Similarly, I can consider modifying Pages.jl so that PlotlyJS methods get loaded if someone is using PlotlyJS:

```julia
> using PlotlyJS
> using Pages
INFO: Loading PlotlyJS methods.
```

This might be the better thing to do. Do you have any thoughts on the subject?

**Comment by sglyon** [comment]
Hey @EricForgy I like your thinking.

In fact, I've already started doing this...

- [here](https://github.com/sglyon/PlotlyJS.jl/blob/4f0c99aed8a5993a08041d02cf4cd631908c4dbb/src/PlotlyJS.jl#L71) for saving eps/png/pdf via Rsvg and Cairo
- [here](https://github.com/sglyon/PlotlyJS.jl/blob/4f0c99aed8a5993a08041d02cf4cd631908c4dbb/src/displays/ijulia.jl#L224-L243) for defining methods on functions from IJulia.jl
- [here](https://github.com/sglyon/PlotlyJS.jl/blob/4f0c99aed8a5993a08041d02cf4cd631908c4dbb/src/display.jl#L123) for integrating with the Atom plots pane
- [here](https://github.com/sglyon/PlotlyBase.jl/blob/c167c9eb8cef2128f2543073022e84e876e6dc17/src/PlotlyBase.jl#L62) for adding trace and plot methods for DataFrames

One of the great things about Requires.jl is that it does not matter which order the packages are loaded.

If package X has a `@require Y ...` statement, then whenever both X and Y are loaded, that code will be run. It could happen in the order `using Y; using X` or `using X; using Y` and it will work the same. 


So, if you were to put your `@require Pages ...` code inside PlotlyJS.jl (which -- btw -- I am totally open to), then you wouldn't have to make any changes in Pages.jl and whenever both packages have been loaded your integration will be active.

**Pull request closed without merging**
