### PR TITLE
Add Project.toml and Manifest.toml

### PR DESCRIPTION
**Pull request by EricForgy**
🙏 

It's pretty hard to work these days without a Project.toml (and I'm constantly maneuvering among environments using `activate`).

### CODE REVIEW

**Comment by sglyon** [comment]
To be totally honest I don't know when is the right time to ditch require and use toml files.

Is this happening throughout the ecosystem?

**Comment by EricForgy** [comment]
Hi @sglyon 👋 

It's been a while 😊 Hope all is well.

It is not one or the other. While we still rely on METADATA for registering new packages and tagging old packages, we're still stuck with `REQUIRE`. However, a lot of the cool new stuff does now work unless you have a `Project.toml`, for example, you cannot `activate` an environment unless it has a `Project.toml`.

This PR doesn't remove the `REQUIRE` file, it just adds the .toml files so everything works.

I expect (hope 🙏) METADATA gets retired soon and we can move to the new General registry so it makes sense to get .toml files ready.

**Comment by EricForgy** [comment]
If you're open to this, I can get the tests to pass. I'm 90% sure the appveyor / travis scripts just needs updating.

**Comment by sglyon** [comment]
Thanks @EricForgy good to hear from you ytoo

I have used PlotlyJS in  environments without any problems. i needed to `activate` my environment, `add PlotlyJS` and things just worked.  Because of that I don't believe we need the Project.toml here in order to use it from another environment. 

I do see what you are saying though that you can't enter the PlotlyJS repo directory and try to `activate` it as a project/environment.

**Comment by EricForgy** [comment]
> I have used PlotlyJS in environments without any problems. i needed to activate my environment, add PlotlyJS and things just worked. Because of that I don't believe we need the Project.toml here in order to use it from another environment.

I can see how this can work if you keep one environment and throw everything you dev into it, but I don't want to work that way (I have close to 10 public / private packages currently under development) . I like to keep specific environments for each specific task I'm working on. It makes sense to just activate the project I want to submit a PR to, but that only works if there is a Project.toml 🤔 

It sounds like you're not interested in this PR. That is fine. It just means I need a keep a local Project.toml for myself. 

By the way, the reason I'm looking at PlotlyJS.jl is because I am developing a package that uses HTTP.jl v0.8.0, but PlotlyJS.jl has an indirect dependency on WebSockets.jl and WebSockets.jl cannot be installed with HTTP.jl v0.8.0. It means, any package that is using HTTP v0.8.0 cannot use PlotlyJS.jl. Just FYI.

**Comment by sglyon** [comment]
I am definitely interested in a PR that moves to the new/permanent system. However, I tried to do this myself a couple months ago and received feedback that until the REQUIRE based system was officially retired it would be best not to introduce (Project|Manifest).toml. IIRC the reasons for waiting were METADATA couldn't handle seeing both REQUIRE and the tomls (probably resolved now), REQUIRE is still necessary for using METADATA, and if I want to distribute my packages through the general repository/METADATA I need to have a REQUIRE. Trying to keep both the tomls and require up to date seemed to add complexity with 0 added benefit (and some detriment at the time). My questions in the response stemmed from that experience and I was wondering if we have reached that retirement date.

I still don't feel that I understand the concern. I have PlotlyJS has a dependency in multiple private projects (that all use the (Project|Manifest).toml system) and haven't had a problem. I can `activate` any of them and it has just worked. Doing `add PlotlyJS` within the projects to add the dependency didn't come with any issues. 

Have you tried to `add PlotlyJS` from within the  environments/projects/packages? From my experience, It should work without having toml files in this repo.

Thanks for looking into PlotlyJS and WebSockets. I don't have the spare cycles myself at the moment push forward in that direction, so the help is very much appreciated.

**Comment by EricForgy** [comment]
> (probably resolved now)

Yeah. This is resolved now 👍 

> I still don't feel that I understand the concern. I have PlotlyJS has a dependency in multiple private projects (that all use the (Project|Manifest).toml system) and haven't had a problem.

Yeah. I didn't explain clearly.

If you have another package (public or private) and THAT package has a Project.toml, there is no issue.

And if you have an environment like the default `v1.1` and you just want to `dev` everything from there, there is no issue.

The only issue is if you want want to `activate` PlotlyJS.jl. If I know I am going to be doing some work on a package, I like to just activate that package directly rather than maintain some massive environment with a giant Manifest.toml that contains nearly every registered package in existence. Doing that - and knowing myself - I could be (and have been) inadvertently working on a `dev`ed version of one of the dependencies. To me, it is much safer to just `activate` a package if I am going to be working on it.

I wouldn't classify this as a major issue. For sure it is minor, but it is enough of an issue - for me at least - that I went ahead and prepared and submitted a PR 😊 

Not a big deal. Like said, I can just use a temp Project.toml if I want to submit a PR.

**Pull request closed without merging**
