### PR TITLE
RFC: pre json filters  for `Plot`s

### PR DESCRIPTION
**Pull request by sglyon**
Here's an idea I'm experimenting with, but am not 100% sold on.

I've added a global:

``` julia
const _pre_json_filters = Dict{Symbol,Function}()
```

That will collect functions with the signature `f(::Plot)`. The idea is that immediately before displaying a plot (using any frontnbd (electron or the notebook)), all functions in `values(_pre_json_filters)` will be called to filter the plot before display.

Some cool things this enables in a pretty straightforward way:
- setting [color cycles](https://github.com/spencerlyon2/PlotlyJS.jl/blob/0398f6043efa67db0f89ddffe786b6cccf87b0d7/src/filters.jl#L8-L25) a la matplotlib
- Creating Gadfly-esque themes or matplotlib-esque [styles](https://github.com/spencerlyon2/PlotlyJS.jl/blob/0398f6043efa67db0f89ddffe786b6cccf87b0d7/src/filters.jl#L42-L65)
- Processing special types of data. @ssfrr had an example of adding a `layout.ticksuffix` when `x` or `y` for a trace was a `Vector{T<:SIQuantity}`. We could also handle converting `Colors.Colorants` to hex strings. The main value of doing these things this way is that we can isolate interactions with other packages in an `@require` block
- Swapping out similar filters by changing the value associated with a particular `key` in the dict (e.g. swapping color cycles)
- completely removing filters by just `pop!`ing the key off the dict

Some downsides:
- We rely on a **_mutable global_** (:shudder:) that mutates plot objects when they are displayed. I see at least two problems with this:
  1. a mutable global can lead to inconsistent behavior across sessions (what if I loaded a package that triggered a new filter in the previous session, but I haven't done that in the current session?)
  2. `display` becomes an impure function as the `Plot` object passed in will not be the same before and after calling `display`

Any comments?

cc: @cc7768 @tbreloff @ssfrr @MikeInnes @malmaud

### CODE REVIEW

**Comment by spencerlyon2** [comment]
Example of using the `ggplot` style:

```julia
using PlotlyJS
p = plot([scatter(y=rand(10)), scatter(y=rand(10)), 
          scatter(y=rand(10)), scatter(y=rand(10))])
display(p)
```

before_ggplot

```julia
close(p)
use_style!(:ggplot)
display(p)
```
after_ggplot

**Comment by malmaud** [comment]
This looks cool! What about some kind of option to `plot` to override/disable the filters on a plot-by-plot basis, so that if it's important to you can be guaranteed `plot`is purely declarative?

There's also a broader question: this is going beyond wrapping plotly.js by adding new (useful) functionality. That's fine with me, but something to be explicitly aware of.

**Comment by cc7768** [comment]
I really like this -- Looks very nice. I had some hesitations about inserting a mutable global, but after thinking about it (and @spencerlyon2 pointing it out) there are lots of plotting packages that allow things like this for the exact reason you're proposing (though this also seems more flexible in good ways).

I think @malmaud is right that it steps a bit beyond `plotly.js`, but I think the proposal is a very useful and flexible step and am also in favor of it.

**Comment by spencerlyon2** [comment]
That's very true, but I think we're beyond only wrapping plotly.js:

- We have multiple frontend integrations
- saving plots to png, pdf, eps, json, svg, etc.

I think the vision for the package needs to be the two fold goal I have on the opening page of the docs:

1. Make it convenient to construct and manipulate plotly visualizations in Julia
2. Provide infrastructure for viewing plots on multiple frontends and saving plotly graphics to files


I believe this feature directly addresses point 1.

I also want to point out one thing about this feature: I've shown applications of automatically restyling a plot before display, but that just scratches the surface. Really what this enables is any functionality that can be defined in a function with signature `f(::Plot)` can be automatically called before display. This could be saving json of the plot, posting to plotly via the rest API, adding a special annotation with your signature to the corner, etc.

**Comment by ssfrr** [comment]
I think the concern about mutating the Plot as a side-effect of `display` is definitely valid. One problem is that we can't distinguish manually-set properties from those that may have been set by a previous run of a filter.

For instance, my SIUnits filter adds a `ticksuffix` property to display the units on the ticks, and throws an error if different traces require different tick labels. It also throws an error if there's an existing `ticksuffix` property that doesn't match, because we don't want to overwrite something the user manually requested. What happens though if you plot a trace (which sets the `ticksuffix`) then swap out that trace for one with a different unit? The old `ticksuffix` will be around and will thrown an error when you try to plot.

Perhaps `display` should create a copy of the plot before running it through the filters, so the filters are always starting with a fresh manually-created plot with no state from previous runs.

**Comment by tbreloff** [comment]
I'm sure you can guess my response... that this is what Plots is for!  It would be slightly annoying to have cool functionality that only works with Plotly... but I will always have a biased view of the world...

**Comment by MikeInnes** [comment]
Like others I really like what this enables but share the concerns about global mutable variables etc., but without thinking about it a lot more I'm not sure what the alternative. To try and spark some thoughts, a couple other starting points might be:

* Treating filters as a part of the plot via an extra `filters` parameter for example, perhaps with a global default when none are provided
* Perhaps using some kind of dynamic binding, with the API above as a convenience?

I'm not sure yet but this seems like a great idea and it'd be cool to make it a really first-class feature.

**Comment by malmaud** [comment]
That `filters` parameter is what I was thinking of in my comment - it does seem important.

**Comment by spencerlyon2** [comment]
Ping to revive the conversation.

I still think something like this would be very cool. I don't want to go as far as re-implementing a substantial chunk of the Plots pipeline, but I would like to be able to support things like styles and other "automatic" transformations within PlotlyJS.jl.

**Pull request closed without merging**
